default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: habicus
  pool: pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: habicus
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: habicus
  pool: 5
  timeout: 5000
