default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: habicus_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: habicus_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: habicus_prod
  pool: 5
